#!/bin/bash

# to use, run following command:
#
# $ sudo auto_mate
#
# this will create a pow file, a apache virtual host file, restart apache, restart pow.

red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

# User must specify a directory
read -p "Project name: " project

if [ ! ${project} ]; then
    printf "%s\n" "${red}Project name is required${end}"
    exit 1
fi

# User must specify an optional subfolder
read -p "Subfolder (or press enter to leave blank): " sub_directory

sub=""

if [[ ${sub_directory} ]]; then
  sub="/${sub_directory}"
fi

sudo echo "<VirtualHost *:80>
    DocumentRoot '${HOME}/code/${project}${sub}'
    ServerName ${project}.dev
</VirtualHost>" > /etc/apache2/sites-available/"${project}".conf

sudo ln -s /etc/apache2/sites-available/${project}.conf /etc/apache2/sites-enabled/${project}.conf
sudo echo '127.0.0.1:80' > ~/.pow/${project}
sudo apachectl restart
powder up

printf "%s\n" "${grn}Environment ready. Go to: http://${project}.dev${end}"

exit 0
