#!/bin/bash

# all you have to do is run (from the same directory as this file) eg:
#
# $ sudo ./auto_mate example
# $ sudo ./auto_mate example public
#
# this will create a pow file, a apache virtual host file, restart apache, restart pow.

if [[ -z $2 ]]
then
  sub=""
else
  sub="/$2"
fi

sudo echo "<VirtualHost *:80>
    DocumentRoot '/Users/mike/code/$1$sub'
    ServerName $1.dev
</VirtualHost>" > /etc/apache2/sites-available/$1.conf

sudo ln -s /etc/apache2/sites-available/$1.conf /etc/apache2/sites-enabled/$1.conf
sudo echo '127.0.0.1:80' > ~/.pow/$1
sudo apachectl restart
powder up
