#!/bin/bash

downloads=(/Users/mike/Downloads/*)

IFS=$'\n' read -d '' -r -a items < $1

# for each dir in Downloads
for (( i = 0; i < ${#downloads[@]}; i++ )); do

    # get the dir name
    dir="${downloads[$i]##*/}"
    # replace dir name with periods
    dir_name=${dir// /.}

    # for each item in array
    for (( j = 0; j < ${#items[@]}; j++ )); do

        # check if part of the name of the dir matches any in the array
        # @todo - make case insensitive
        if [[ "${dir_name}" == *"${items[$j]}"* ]]; then

            # @todo - allow for spaces

            # if it does, then go in to the dir
            for file in "${downloads[$i]}"/*; do
                if [[
                    "${file}" == *".mkv"* ||
                    "${file}" == *".mp4"* ||
                    "${file}" == *".avi"*
                ]]; then
                    # @todo - check file does not already exist
                    # @todo - check folder already exists. create it if it doesn't
                    echo "moving $file to /Users/mike/media/${items[$j]}/"
                    # and move them in to a dir with the same name from the array element that was matched
                    mv $file "/Users/mike/media/${items[$j]}/"
                fi
            done

            # then after you've taken everything, just delete that directory
            rm -rf "${downloads[$i]}"
        fi
    done
done

exit
