#!/bin/bash

# to use, run following command:
#
# $ clean_downloads <filename.txt>
#
# This will clean your downloads for you.

in_array() {

    # echo ${1}[@]
    # exit

    local haystack=${1}[@]
    local needle=${2}

    echo ${!haystack}
    exit

    for i in ${!haystack}; do
        if [[ ${i} == ${needle} ]]; then
            return 0
        fi
    done

    return 1
}

downloads=(${HOME}/Downloads/*)

IFS=$'\n' read -d '' -r -a items < $1

for (( j=0; j<${#downloads[@]}; j++ )); do

    dir_original_name="${downloads[$j]##*/}"
    downloads_directory_name=${downloads[$j]}
    dir_name=${dir_original_name// /.}

    if in_array items ${dir_name}; then

        media_dir_location="${HOME}/media/${dir_name}"

        for file in "${downloads_directory_name}"/*; do
            if [[
                "${file}" == *".mkv"* ||
                "${file}" == *".mp4"* ||
                "${file}" == *".avi"*
            ]]; then
                if [[ ! -d ${media_dir_location} ]]; then
                    if mkdir ${media_dir_location}; then
                        echo "Created new directory in /media called: ${dir_name}."
                    else
                        echo "Error: Could not create ${dir_name} in /media."
                        exit 1
                    fi
                fi

                echo "Moving the file ${file} to ${media_dir_location}."
                mv ${file} ${media_dir_location}
            fi
        done

        echo "Deleting the directory: ${downloads_directory_name}"
        rm -rf ${downloads_directory_name}
    fi
done

exit 0
