#!/bin/bash

repositories=(/Users/mike/code/*)
sites_available_conf=(/etc/apache2/sites-available/*.conf)
sites_enabled_conf=(/etc/apache2/sites-enabled/*.conf)
pow=(/Users/mike/.pow/*)

function remove_files() {
    arr=("$@")
    for i in "${arr[@]}"; do
        path_to_file="${i}"
        directory_name="${path_to_file##*/}"
        if ! [[ "${repositories[*]}" == *"${directory_name%.*}"* ]]; then
            echo "removing.... ${path_to_file}"
            sudo rm ${path_to_file}
        fi
    done
}

remove_files "${sites_enabled_conf[@]}"
remove_files "${sites_available_conf[@]}"
remove_files "${pow[@]}"

sudo apachectl restart
powder up

exit
