#!/bin/bash

# to use, run following command:
#
# $ tidy_up
#
# This will remove pow files and virtual host files that are not being used.

red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

in_array() {
    local haystack=${1}[@]
    local needle=${2}

    for i in ${!haystack}; do

        folder_name="${i##*/}"

        if [[ ${folder_name} == ${needle} ]]; then
            return 0
        fi
    done

    return 1
}

remove_files() {
    arr=("$@")
    for i in "${arr[@]}"; do
        path_to_file="${i}"
        directory_name="${path_to_file##*/}"
        directory="${directory_name%.*}"

        if ! in_array repositories ${directory} ; then
            printf "%s\n" "${red}Deleting file: ${path_to_file}${end}"
            sudo rm ${path_to_file}
        fi
    done
}

repositories=(${HOME}/code/*)
sites_available_conf=(/etc/apache2/sites-available/*.conf)
sites_enabled_conf=(/etc/apache2/sites-enabled/*.conf)
pow=(${HOME}/.pow/*)

printf "%s\n" "${blu}Looping through sites-enabled directory${end}"
remove_files "${sites_enabled_conf[@]}"

printf "%s\n" "${blu}Looping through sites-available directory${end}"
remove_files "${sites_available_conf[@]}"

printf "%s\n" "${blu}Looping through .pow directory${end}"
remove_files "${pow[@]}"

printf "%s\n" "${grn}Restarting apache${end}"
sudo apachectl restart

printf "%s\n" "${grn}Powdering up${end}"
powder up

exit 0
